version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - XWIKI_VERSION=${XWIKI_VERSION}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=<azure_mysql_host>
    volumes:
      - xwiki-data:/usr/local/xwiki
  db:
    image: "mysql:8.3"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
volumes:
  xwiki-data: {}
